common:
  path_prefix: /loki

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1  
  chunk_idle_period: 5m
  max_chunk_age: 1h
  chunk_target_size: 4194304  # 4MB chunk size
  wal:
    enabled: true
    dir: /loki/wal

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

limits_config:
  enforce_metric_name: false
  ingestion_rate_mb: 20
  ingestion_burst_size_mb: 40
  max_streams_per_user: 10000
  per_stream_rate_limit: "5MB"
  per_stream_rate_limit_burst: "20MB"


chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h  # 7 days retention
