server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    headers:
      X-Scope-OrgID: "fake"
scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    pipeline_stages:
      - cri: {}
      - match:
          selector: '{container_name!=""}'
          stages:
            - template:
                source: labels
                template: '{{.container_name}}|{{.service}}|{{.project}}'
                output: debug_info
    # ADD THIS FILTER to exclude promtail's own logs
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: promtail
        action: drop
      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        target_label: container_name
        replacement: '$1'
      # Try these alternative label sources:
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service
      - source_labels: [__meta_docker_container_label_com_docker_compose_project]
        target_label: project