apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
  labels:
    app: psmarket
    component: kafka
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/kafka
  # For Azure migration, replace hostPath with a StorageClass/PVC

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
  labels:
    app: psmarket
    component: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: kafka-pv

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: psmarket
    component: kafka
    tier: backend
  annotations:
    description: "Kafka (single-node KRaft mode)"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psmarket
      component: kafka
  template:
    metadata:
      labels:
        app: psmarket
        component: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.6.0
          ports:
            - containerPort: 9092
            - containerPort: 9093
            - containerPort: 29092
          env:
            - name: KAFKA_CLUSTER_ID
              value: "VJ7gkKpd-kqlYxyp4xx8zw"
            - name: CLUSTER_ID
              value: "VJ7gkKpd-kqlYxyp4xx8zw"
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@kafka:9093"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:29092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_LOG_DIRS
              value: "/var/lib/kafka/data"
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
          # resources:
          #   requests:
          #     cpu: "200m"
          #     memory: "512Mi"
          #   limits:
          #     cpu: "1"
          #     memory: "2Gi"
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: psmarket
    component: kafka
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
    - port: 9093
      targetPort: 9093
    - port: 29092
      targetPort: 29092
  selector:
    app: psmarket
    component: kafka
