apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    app: psmarket
    component: mongo
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mongo
  # For Azure migration, replace hostPath with a StorageClass/PVC

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  labels:
    app: psmarket
    component: mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: mongo-pv

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: psmarket
    component: mongo
    tier: backend
  annotations:
    description: "MongoDB for product catalog and notification"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psmarket
      component: mongo
  template:
    metadata:
      labels:
        app: psmarket
        component: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "256Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "1Gi"
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: psmarket
    component: mongo
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: psmarket
    component: mongo
