apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    app: psmarket
    component: postgres
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgres
  # For Azure migration, replace hostPath with a StorageClass/PVC

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: psmarket
    component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: postgres-pv
  # For Azure, remove 'volumeName' and set 'storageClassName' appropriately

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: psmarket
    component: postgres
    tier: backend
  annotations:
    description: "Postgres database for core services"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psmarket
      component: postgres
  template:
    metadata:
      labels:
        app: psmarket
        component: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "orders"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          # Uncomment below for resource limits
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "256Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "1Gi"
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: psmarket
    component: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: psmarket
    component: postgres
