apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: psmarket
    component: redis
    tier: backend
  annotations:
    description: "Redis for caching and notification"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psmarket
      component: redis
  template:
    metadata:
      labels:
        app: psmarket
        component: redis
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
          # resources:
          #   requests:
          #     cpu: "50m"
          #     memory: "128Mi"
          #   limits:
          #     cpu: "250m"
          #     memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: psmarket
    component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: psmarket
    component: redis
