name: Deploy to Azure App Service

on:
  workflow_dispatch:  # Manual run trigger
# Uncomment below for auto triggers on push to main branch
# push:
#   branches:
#     - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        id: azurelogin
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS || '' }}
          enable-AzPSSession: false

      - name: Check login success
        run: |
          if [ -z "${{ secrets.AZURE_CREDENTIALS }}" ]; then
            echo "##[error]No AZURE_CREDENTIALS secret found. Please set it or login interactively."
            exit 1
          fi

      - name: Run deployment script
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          ACR_NAME: ${{ secrets.ACR_NAME }}
        run: |
          chmod +x ./create-app-service.sh
          ./create-app-service.sh
