apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-gateway-logs-pv
  labels:
    app: psmarket
    component: api-gateway
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/api_gateway/logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-gateway-logs-pvc
  labels:
    app: psmarket
    component: api-gateway
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: api-gateway-logs-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: psmarket
    component: api-gateway
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psmarket
      component: api-gateway
  template:
    metadata:
      labels:
        app: psmarket
        component: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: api_gateway:latest
          envFrom:
            - configMapRef:
                name: api-gateway-config
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: logs
              mountPath: /var/log/api_gateway
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "128Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "512Mi"
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: api-gateway-logs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    app: psmarket
    component: api-gateway
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080 # Access via minikube:30080
  selector:
    app: psmarket
    component: api-gateway
