apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-service-logs-pv
  labels:
    app: psmarket
    component: auth-service
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/auth_service/logs
  # For Azure migration: use a StorageClass and PVC instead of hostPath

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-service-logs-pvc
  labels:
    app: psmarket
    component: auth-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: auth-service-logs-pv

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: psmarket
    component: auth-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psmarket
      component: auth-service
  template:
    metadata:
      labels:
        app: psmarket
        component: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth_service:latest
          envFrom:
            - configMapRef:
                name: auth-service-config
            # For secrets, use secretRef
          ports:
            - containerPort: 8009
          volumeMounts:
            - name: logs
              mountPath: /var/log/auth_service
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "128Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "512Mi"
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: auth-service-logs-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: psmarket
    component: auth-service
spec:
  type: ClusterIP
  ports:
    - port: 8009
      targetPort: 8009
  selector:
    app: psmarket
    component: auth-service
