apiVersion: v1
kind: PersistentVolume
metadata:
  name: delivery-service-logs-pv
  labels:
    app: psmarket
    component: delivery
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/delivery/logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: delivery-service-logs-pvc
  labels:
    app: psmarket
    component: delivery
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: delivery-service-logs-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
  labels:
    app: psmarket
    component: delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psmarket
      component: delivery
  template:
    metadata:
      labels:
        app: psmarket
        component: delivery
    spec:
      containers:
        - name: delivery
          image: delivery:latest
          envFrom:
            - configMapRef:
                name: delivery-config
          ports:
            - containerPort: 8006
          volumeMounts:
            - name: logs
              mountPath: /var/log/delivery_service
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "128Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "512Mi"
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: delivery-service-logs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: delivery
  labels:
    app: psmarket
    component: delivery
spec:
  type: ClusterIP
  ports:
    - port: 8006
      targetPort: 8006
  selector:
    app: psmarket
    component: delivery
