apiVersion: v1
kind: PersistentVolume
metadata:
  name: inventory-service-logs-pv
  labels:
    app: psmarket
    component: inventory
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/inventory/logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inventory-service-logs-pvc
  labels:
    app: psmarket
    component: inventory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: inventory-service-logs-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  labels:
    app: psmarket
    component: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psmarket
      component: inventory
  template:
    metadata:
      labels:
        app: psmarket
        component: inventory
    spec:
      containers:
        - name: inventory
          image: inventory:latest
          envFrom:
            - configMapRef:
                name: inventory-config
          ports:
            - containerPort: 8002
          volumeMounts:
            - name: logs
              mountPath: /var/log/inventory_service
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "128Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "512Mi"
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: inventory-service-logs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: inventory
  labels:
    app: psmarket
    component: inventory
spec:
  type: ClusterIP
  ports:
    - port: 8002
      targetPort: 8002
  selector:
    app: psmarket
    component: inventory
