apiVersion: v1
kind: PersistentVolume
metadata:
  name: payment-service-logs-pv
  labels:
    app: psmarket
    component: payment
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/payment/logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-service-logs-pvc
  labels:
    app: psmarket
    component: payment
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: payment-service-logs-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: psmarket
    component: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psmarket
      component: payment
  template:
    metadata:
      labels:
        app: psmarket
        component: payment
    spec:
      containers:
        - name: payment
          image: payment:latest
          envFrom:
            - configMapRef:
                name: payment-config
          ports:
            - containerPort: 8004
          volumeMounts:
            - name: logs
              mountPath: /var/log/payment_service
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "128Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "512Mi"
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: payment-service-logs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app: psmarket
    component: payment
spec:
  type: ClusterIP
  ports:
    - port: 8004
      targetPort: 8004
  selector:
    app: psmarket
    component: payment
