name: CI - Build, Deploy, and Test Docker Compose

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      run_tests:
        description: 'Run tests? Set false to skip tests'
        required: false
        default: 'false'  # tests disabled by default
concurrency:
  group: ci-build-deploy-test
  cancel-in-progress: true

jobs:
  build-deploy-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: orders
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      mongo:
        image: mongo:6
        env:
          MONGO_INITDB_DATABASE: admin
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")' --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 27017:27017

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
      kafka:
        image: confluentinc/cp-kafka:7.6.0
        env:
          KAFKA_CLUSTER_ID: "VJ7gkKpd-kqlYxyp4xx8zw"
          KAFKA_NODE_ID: 1
          KAFKA_PROCESS_ROLES: broker,controller
          KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:29092
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
          KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
          KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_LOG_DIRS: /var/lib/kafka/data
        ports:
          - 9092:9092
        options: >-
          --health-cmd "kafka-topics --bootstrap-server localhost:9092 --list"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10



    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # - name: Login to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Install kafkacat for Kafka health checks
      run: |
        sudo apt-get update
        sudo apt-get install -y kafkacat

    - name: Diagnostic - Check port 27017 usage and running containers
      run: |
        echo "Listening TCP ports:"
        sudo netstat -tulpn | grep LISTEN || true

        echo "Check ports 5432, 27017, 6379, 9092 specifically:"
        for port in 5432 27017 6379 9092; do
          echo "Port $port usage:"
          sudo lsof -i :$port || echo "Port $port not in use"
        done

        echo "List all running Docker containers:"
        docker ps

    - name: Cleanup Docker environment
      run: |
        echo "Prune unused containers, networks, volumes, images"
        docker system prune -af

    - name: Build Docker images
      working-directory: ./
      run: docker compose build

    # - name: Push Docker images
    #   run: docker compose push
    - name: Prepare log directories for volume mounts
      run: |
        mkdir -p ./logs/auth_service/logs
        mkdir -p ./logs/product_catalog/logs
        mkdir -p ./logs/inventory/logs
        mkdir -p ./logs/order/logs
        mkdir -p ./logs/payment/logs
        mkdir -p ./logs/billing/logs
        mkdir -p ./logs/delivery/logs
        mkdir -p ./logs/notification/logs
        mkdir -p ./logs/notification_bridge/logs
        mkdir -p ./logs/store_onboarding/logs
        mkdir -p ./logs/api_gateway/logs
        
    - name: Start Docker Compose services
      working-directory: ./    
      run: docker compose up -d

    - name: Make wait-for-services.sh executable
      run: chmod +x ./scripts/wait-for-services.sh

    - name: Wait for services to be healthy
      run: ./scripts/wait-for-services.sh

    - name: Run tests (conditional)
      if: ${{ github.event.inputs.run_tests == 'true' }}
      run: |
        # Run tests and capture exit code
        docker compose exec auth_service pytest ./test
        TEST_EXIT_CODE=$?
        
        # Even if tests fail, we want to continue to tear down
        if [ $TEST_EXIT_CODE -ne 0 ]; then
          echo "Tests failed with exit code $TEST_EXIT_CODE"
          echo "TEST_FAILURE=true" >> $GITHUB_ENV
        fi

    - name: Check test results
      if: ${{ github.event.inputs.run_tests == 'true' && env.TEST_FAILURE == 'true' }}
      run: |
        echo "Tests failed - failing workflow"
        exit 1        

    - name: Tear down Docker Compose services
      working-directory: ./       
      if: always()
      run: docker compose down

    - name: Cleanup workspace - logs and temp files
      if: always()
      run: |
        docker system prune -af     
        echo "Cleaning up logs and temporary files..."
        rm -rf ./logs
        rm -rf ./temp || true      
